services:
  frontend:
    image: marzban-seller-panel-frontend:dev
    restart: always
    volumes:
      - ./data:/frontend/data
    #   - ./public/logo.gif:/frontend/logo.gif
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: marzban-seller-panel-backend:dev
    restart: always
    env_file: .env
    volumes:
      - ./certs:/backend/certs
    ports:
      - 8000:8443

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 8443:8443
    depends_on:
      - frontend