services:
  marzban-seller-panel-frontend:
    image: mehdizadehasma/marzban-seller-panel-frontend:latest
    restart: always
    volumes:
      - ./config.json:/frontend/data/config.json
      - ./logo.gif:/frontend/logo.gif
    ports:
      - 3000:3000
    depends_on:
      - marzban-seller-panel-backend

  marzban-seller-panel-backend:
    image: mehdizadehasma/marzban-seller-panel-backend:latest
    restart: always
    env_file: .env
    volumes:
      - ./certs:/backend/certs
    ports:
      - 8000:8443

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 8443:8443
    depends_on:
      - marzban-seller-panel-frontend